### ISSUE TITLE
The reason for ubuntu docker image?

### ISSUE THREAD

**Issue by sinansonmez** [gitpod-samples/rust-hello-world#1]
@axonasif Just out of curiosity, is there any specific reason you used ubuntu docker image for this template?

**Comment by axonasif** [comment]
Hi @sinansonmez,

This repo was mainly created for using with https://www.youtube.com/watch?v=oTFbDRi4S84 , at the last step I show an example of configuring a dockerfile with a non-gitpod base image (hence ubuntu).

**Comment by sinansonmez** [comment]
nice, thanks for the answer @axonasif
